apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::654848625567:role/eksctl-eksctl-demo-nodegroup-ng-b-NodeInstanceRole-GEDMOQ9641OD
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-04T15:56:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1723"
  uid: 81f61735-963d-467b-8d04-05409d1e1f4d
