apiVersion: v1
data:
  mapRoles: "- groups:\n  - system:masters\n  rolearn: arn:aws:iam::654848625567:role/UdacityFlaskDeployCBKubectlRole\n
    \ username: build \n- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn:
    arn:aws:iam::654848625567:role/eksctl-eksctl-demo-nodegroup-ng-b-NodeInstanceRole-GEDMOQ9641OD\n
    \ username: system:node:{{EC2PrivateDNSName}}\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-04T15:56:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "21238"
  uid: 81f61735-963d-467b-8d04-05409d1e1f4d
